### ISSUE TITLE
rake grade issue - would need to set the user.name and user.email for every assignment

### ISSUE THREAD

**Issue by ananthprayaga** [firstdraft/grade_runner#74]
Hi @jelaniwoods ,

I am attaching below an error when I run rake grade in GitPod. I have all my settings for Git within Gitpod set, but I still get the following error:  

![Screen Shot 2023-11-13 at 2 26 56 PM](https://github.com/firstdraft/grade_runner/assets/31409681/1fc307a1-ddee-4db4-b3de-d38a949b5a40)

I have been able to solve this by doing: 

git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"

However, a student would have to do this every time for a new assignment - Is there a way we can resolve this without having them do it each time? 

I noticed you have another very similar issue - not sure if it were to solve the same issue or not - I can delete this and it as a comment to the other [ticket](https://github.com/firstdraft/grade_runner/issues/73) if you prefer.

**Comment by ananthprayaga** [comment]
It seems this must be done each time you restart the gitpod for the same assignment. 

I did it yesterday for an assignment, and when I went to Rake Graded today, it got the error again even though I previously set the GitHub user name and user.email

**Comment by jelaniwoods** [comment]
@ananthprayaga thanks for reporting! I did note this in #73, but it wasn't very detailed.

Before this quarter Gitpod would automatically set these git credentials for you. I'm kind of surprised they removed it, since I imagine you'd need to set these anytime you want to push to GitHub, which I imagine most students need to do for at least their final project.
