### ISSUE TITLE
API rate limit reached

### ISSUE THREAD

**Issue by bpurinton** [firstdraft/grade_runner#75]
https://ask.firstdraft.com/forums/5/posts/8158

Is that expected rake grade behavior? Should we pay for a higher API rate?

**Comment by bpurinton** [comment]
Did some brainstorming, unclear how this happened. Possibly the student was running `rake grade` very rapidly or in two terminals at once? In any case, going to leave this alone for now and revisit if it happens more.

**Comment by bpurinton** [comment]
Just want to note here another occurrence of this issue (on Gitpod, which is maybe where the first person also had an issue?)

via Jake Blumenfield email:

>  I've made some progress and I'm now working on the Photogram GUI project. After following the video step by step, I am encountering this error when running rake grade in Gitpod. Up until the last 15 or so minutes of the video, I was able to run rake grade but it looks like the # of routes may be providing an API overload per the error. Thanks!

![image](https://github.com/firstdraft/grade_runner/assets/12408296/d9ce615b-a609-4268-88ec-b7b992b65426)

**Comment by jelaniwoods** [comment]
Noticed this error a lot in class today. I'll raise the priority of this on my list of issues to tackle.

**Comment by jelaniwoods** [comment]
I'm assuming the [rate limit was updated to 60/hour](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users).

We could possibly add an endpoint to Grades to retrieve a user's PAT (since we store those) and have grade runner lookup the token using the GitHub username and _then_ make the request to download the latest specs. Using the PAT should increase the limit to 5,000 per hour, which I think should be sufficient.

Alternatively:
- we could have Grades make the call for grade runner using the PAT.
- we could maybe save the latest SHA of the spec folder on Grades and have grade runner compare that to the local SHA in order to determine if the API call should be made. This should prevent the majority of API calls from being made in the first place since most students don't change the spec folder. This would also require Grades to have the SHA updated via webhooks so it stays up tot date.
